1. 导入numpy库并简写为 np

In [1]:
import numpy as np

2. 打印numpy的版本和配置说明

In [2]:
print(np.__version__)
np.show_config()

1.15.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HZC/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/HZC/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HZC/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/

3. 创建一个长度为10的空向量

In [3]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. 如何找到任何一个数组的内存大小？

In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


5. 如何从命令行得到numpy中add函数的说明文档?

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

6.创建一个长度为10并且除了第五个值为1的空向量

In [6]:
Z = np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. 创建一个值域范围从10到49的向量

In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8.反转一个向量(第一个元素变为最后一个)

In [8]:
Z = np.arange(10)
Z = Z[::-1]
print(Z)

[9 8 7 6 5 4 3 2 1 0]


9. 创建一个 3x3 并且值从0到8的矩阵

In [9]:
Z = np.arange(0,9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


11. 创建一个 3x3 的单位矩阵

In [11]:
Z =np.eye(3) 
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. 创建一个 3x3x3的随机数组

In [12]:
np.random.random((3,3,3))

array([[[0.36088046, 0.89957569, 0.15628239],
        [0.73545867, 0.18278602, 0.37521014],
        [0.71235814, 0.16758011, 0.74809971]],

       [[0.38854617, 0.01901927, 0.96591212],
        [0.19089537, 0.84459664, 0.68524072],
        [0.77255431, 0.30070436, 0.54761318]],

       [[0.5443357 , 0.30078723, 0.89763846],
        [0.58173887, 0.08784069, 0.04214092],
        [0.50564194, 0.6256752 , 0.50623384]]])

13. 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [13]:
Z = np.random.random((10,10))
np.max(Z),np.min(Z)
#或者Z.max(),Z.min()

(0.985765305750244, 8.344678771243785e-05)

14. 创建一个长度为30的随机向量并找到它的平均值 

In [14]:
Z = np.arange(30)
Z.mean()

14.5

15. 创建一个二维数组，其中边界值为1，其余值为0 

In [15]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. 对于一个存在的数组，如何添加一个用0填充的边界?

In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17. 以下表达式运行的结果分别是什么?

In [17]:
print(0*np.nan)

nan


In [18]:
print(np.nan == np.nan)

False


In [19]:
print(np.inf > np.nan)

False


In [20]:
print(np.nan - np.nan)

nan


In [21]:
print(0.03==3*0.1)

False


18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 

In [22]:
Z = np.diag(1+np.arange(4),-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. 创建一个8x8 的矩阵，并且设置成棋盘样式

In [23]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [24]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


21. 用tile函数去创建一个 8x8的棋盘样式矩阵

In [25]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. 对一个5x5的随机矩阵做归一化
(提示: (x - min) / (max - min))

In [26]:
A = np.random.random((5,5))
b = (A-A.min())/(A.max()-A.min())
print(b)

[[0.71927597 0.49415767 0.87622597 0.19392968 0.2281633 ]
 [0.5869704  0.15014507 0.8381994  0.         0.2242387 ]
 [1.         0.3833143  0.89848779 0.42235699 0.08714507]
 [0.91776926 0.5866586  0.19003679 0.75442703 0.85734494]
 [0.28971173 0.6560925  0.86379106 0.37475493 0.30317099]]


23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？

In [27]:
 color = np.dtype([("r", np.ubyte, 1),
                   ("g", np.ubyte, 1),
                   ("b", np.ubyte, 1),
                   ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？

In [28]:
A = np.arange(15).reshape(5,3)
B = np.arange(6).reshape(3,2)
print(A.dot(B))

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


25. 给定一个一维数组，对其在3到8之间的所有元素取反

In [29]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


26. 下面脚本运行后的结果是什么? (★☆☆)
(提示: np.sum)

In [30]:
print(sum(range(5),-1))

9


In [31]:
from numpy import *
print(sum(range(5),-1))

10


27. 考虑一个整数向量Z,下列表达合法的是哪个?

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [36]:
Z = np.arange(5)
print(Z**Z)

[  1   1   4  27 256]


In [37]:
Z = np.arange(5)
2 << Z >> 2 

array([0, 1, 2, 4, 8], dtype=int32)

In [38]:
Z = np.arange(5)
Z <- Z

array([False, False, False, False, False])

In [39]:
Z = np.arange(5)
1j*Z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [41]:
Z = np.arange(5)
Z/1/1

array([0., 1., 2., 3., 4.])

In [46]:
Z = np.arange(5)
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

28. 下列表达式的结果分别是什么?(★☆☆)

In [47]:
print(np.array(0) / np.array(0))

nan


C:\Users\HZC\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [48]:
print(np.array(0) // np.array(0))

0


C:\Users\HZC\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [49]:
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


29. 如何从零位对浮点数组做舍入 ? (★☆☆)
(提示: np.uniform, np.copysign, np.ceil, np.abs)

In [50]:
Z= np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 3.  3.  4. -3. -6.  4.  8.  4.  1. 10.]


30. 如何找到两个数组中的共同元素? (★☆☆)
(提示: np.intersect1d)

In [51]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 2 3 7]


31. 如何忽略所有的 numpy 警告(尽管不建议这么做)? (★☆☆)
(提示: np.seterr, np.errstate)

In [53]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

#An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

32. 下面的表达式是正确的吗? (★☆☆)
(提示: imaginary number)

In [54]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\HZC\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [56]:
np.sqrt(4)

2.0

33. 如何得到昨天，今天，明天的日期? (★☆☆)
(提示: np.datetime64, np.timedelta64)

In [57]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-08-06
Today is 2019-08-07
Tomorrow is 2019-08-08


34. 如何得到所有与2016年7月对应的日期？ (★★☆)
(提示: np.arange(dtype=datetime64['D'])

In [58]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)? (★★☆)
(提示: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [59]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)

array([3., 3., 3.])

In [60]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [61]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [62]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

36. 用五种不同的方法去提取一个随机数组的整数部分(★★☆)
(提示: %, np.floor, np.ceil, astype, np.trunc)

In [63]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)

[5. 7. 9. 5. 4. 3. 5. 7. 0. 7.]


In [64]:
print (np.floor(Z))

[5. 7. 9. 5. 4. 3. 5. 7. 0. 7.]


In [67]:
print (np.ceil(Z)-1)

[5. 7. 9. 5. 4. 3. 5. 7. 0. 7.]


In [68]:
print (Z.astype(int))

[5 7 9 5 4 3 5 7 0 7]


In [69]:
print (np.trunc(Z))

[5. 7. 9. 5. 4. 3. 5. 7. 0. 7.]


37. 创建一个5x5的矩阵，其中每行的数值范围从0到4 (★★☆)
(提示: np.arange)

In [70]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. 通过考虑一个可生成10个整数的函数，来构建一个数组(★☆☆)
(提示: np.fromiter)

In [74]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 (★★☆)
(提示: np.linspace)

In [83]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. 创建一个长度为10的随机向量，并将其排序 (★★☆)
(提示: sort)

In [84]:
Z = np.random.random(10)
Z.sort()
print (Z)

[0.07531255 0.11581229 0.32734773 0.33966861 0.37267349 0.39057182
 0.47951545 0.58209237 0.85244804 0.9215742 ]


41.对于一个小数组，如何用比 np.sum更快的方式对其求和？(★★☆)
(提示: np.add.reduce)

In [85]:
Z = np.arange(10)
np.add.reduce(Z)

45

42. 对于两个随机数组A和B，检查它们是否相等(★★☆)
(提示: np.allclose, np.array_equal)

In [86]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


In [87]:
equal = np.array_equal(A,B)
print(equal)

False


43. 创建一个只读数组(read-only) (★★☆)
(提示: flags.writeable)

In [88]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式(★★☆)
(hint: np.sqrt, np.arctan2)

In [89]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.93538334 0.48247656 0.95366391 0.79114758 0.59870919 0.7539749
 0.16710801 0.74683768 0.40321702 0.98959248]
[0.57044877 0.85130761 1.09532027 0.6416593  1.35488118 0.24791026
 1.43247561 1.48116975 1.10717904 0.98299013]


45. 创建一个长度为10的向量，并将向量中最大值替换为1 (★★☆)
(提示: argmax)

In [90]:
Z = np.random.random(10)
Z[Z.argmax()] = 1
print (Z)

[0.12532601 0.73350547 0.95881463 0.42136803 0.33556628 1.
 0.21126606 0.03790604 0.36984383 0.86439366]


46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域 (★★☆)
(提示: np.meshgrid)

In [91]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))
(提示: np.subtract.outer)

In [95]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


48. 打印每个numpy标量类型的最小值和最大值？ (★★☆)
(提示: np.iinfo, np.finfo, eps)

In [93]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


49. 如何打印一个数组中的所有数值? (★★☆)
(提示: np.set_printoptions)

In [94]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


50. 给定标量时，如何找到数组中最接近标量的值？(★★☆)
(提示: argmin)

In [100]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

39
