In [1]:
import pandas as pd
import numpy as np

In [3]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2['a']

-5

In [14]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

In [15]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [16]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [21]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [26]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [27]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [31]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [32]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [33]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [34]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [35]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [38]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [39]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [40]:
obj.index = ['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [42]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
       'years':[2000,2001,2002,2001,2002,2003],
       'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)

In [43]:
frame

state  years  pop
0    Ohio   2000  1.5
1    Ohio   2001  1.7
2    Ohio   2002  3.6
3  Nevada   2001  2.4
4  Nevada   2002  2.9
5  Nevada   2003  3.2

In [44]:
frame.head()

state  years  pop
0    Ohio   2000  1.5
1    Ohio   2001  1.7
2    Ohio   2002  3.6
3  Nevada   2001  2.4
4  Nevada   2002  2.9

In [45]:
pd.DataFrame(data,columns = ['years','state','pop'])

years   state  pop
0   2000    Ohio  1.5
1   2001    Ohio  1.7
2   2002    Ohio  3.6
3   2001  Nevada  2.4
4   2002  Nevada  2.9
5   2003  Nevada  3.2

In [47]:
frame2 = pd.DataFrame(data,columns = ['years','state','pop','debt'],
            index = ['one','two','three','four','five','six'])
frame2

years   state  pop debt
one     2000    Ohio  1.5  NaN
two     2001    Ohio  1.7  NaN
three   2002    Ohio  3.6  NaN
four    2001  Nevada  2.4  NaN
five    2002  Nevada  2.9  NaN
six     2003  Nevada  3.2  NaN

In [48]:
frame2.columns

Index(['years', 'state', 'pop', 'debt'], dtype='object')

In [49]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [51]:
frame2.years

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: years, dtype: int64

In [52]:
frame2.loc['three']

years    2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [54]:
frame2['debt'] = 16.5
frame2

years   state  pop  debt
one     2000    Ohio  1.5  16.5
two     2001    Ohio  1.7  16.5
three   2002    Ohio  3.6  16.5
four    2001  Nevada  2.4  16.5
five    2002  Nevada  2.9  16.5
six     2003  Nevada  3.2  16.5

In [56]:
frame2.debt = np.arange(6.)
frame2

years   state  pop  debt
one     2000    Ohio  1.5   0.0
two     2001    Ohio  1.7   1.0
three   2002    Ohio  3.6   2.0
four    2001  Nevada  2.4   3.0
five    2002  Nevada  2.9   4.0
six     2003  Nevada  3.2   5.0

In [57]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

years   state  pop  debt
one     2000    Ohio  1.5   NaN
two     2001    Ohio  1.7  -1.2
three   2002    Ohio  3.6   NaN
four    2001  Nevada  2.4  -1.5
five    2002  Nevada  2.9  -1.7
six     2003  Nevada  3.2   NaN

In [60]:
frame2['eastern'] = frame2.state =='Ohio'
frame2

years   state  pop  debt  eastern
one     2000    Ohio  1.5   NaN     True
two     2001    Ohio  1.7  -1.2     True
three   2002    Ohio  3.6   NaN     True
four    2001  Nevada  2.4  -1.5    False
five    2002  Nevada  2.9  -1.7    False
six     2003  Nevada  3.2   NaN    False

In [61]:
del frame2['eastern']

In [62]:
frame2.columns

Index(['years', 'state', 'pop', 'debt'], dtype='object')

In [68]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}


In [67]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [65]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [76]:
pdata = {'Ohio': frame3['Ohio'][:-1],
'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [78]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [79]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [81]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [83]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [84]:
index[1:]

Index(['b', 'c'], dtype='object')

In [86]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [88]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [89]:
obj2.index is labels

True

重新索引

In [90]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [91]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [92]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [93]:
obj3.reindex(range(6),method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [95]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=['a', 'c', 'd'],
                     columns = ['Ohio', 'Texas', 'California'])
frame


Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [96]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [97]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [98]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

丢弃某条轴上的一个或多个项很简单，只要有一个索引数组或列表即可。由于需要执行一些数据整理和集合逻辑，所 以drop方法返回的是一个在指定轴上删除了指定值的新对象：

In [99]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [101]:
new_obj=obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [102]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [103]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [104]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [105]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [106]:
obj['b']

1.0

In [108]:
obj[1]

1.0

In [109]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [110]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [111]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

利用标签的切片运算与普通的Python切片运算不同，其末端是包含的：

In [112]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [115]:
obj['b':'c'] =5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [116]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
              index=['Ohio', 'Colorado', 'Utah', 'New York'],
              columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [117]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [118]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [119]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [120]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

对于DataFrame的行的标签索引，我引入了特殊的标签运算符loc和iloc。它们可以让你用类似NumPy的标记，使用 轴标签（loc）或整数索引（iloc），从DataFrame选择行和列的子集。

In [121]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

用iloc和整数进行选取

In [122]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [123]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [124]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [125]:
ser[-1]

KeyError: -1

对于非整数索引，不会产生歧义

In [127]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [128]:
ser2[-1]

2.0

In [129]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [130]:
ser[:1]

0    0.0
dtype: float64

In [131]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [132]:
ser.iloc[:1]

0    0.0
dtype: float64

In [133]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
index=['Ohio', 'Texas', 'Colorado'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [135]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

因为'c'和'e'列均不在两个DataFrame对象中，在结果中以缺省值呈现。行也是同样。 如果DataFrame对象相加，没有共用的列或行标签，结果都会是空

In [136]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [3]:
df1 = pd.DataFrame({'A': [1, 2]})
df1

A
0  1
1  2

In [5]:
df2 = pd.DataFrame({'B': [3, 4]})
df2

B
0  3
1  4

In [6]:
c = df1-df2
c

A   B
0 NaN NaN
1 NaN NaN

In [7]:
c.fillna(1)

A    B
0  1.0  1.0
1  1.0  1.0

In [9]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [10]:
arr[0]

array([0., 1., 2., 3.])

从arr减去arr[0]，每一行都会执行这个操作。这就叫做广播（broadcasting）

In [11]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])